### ISSUE TITLE
Array of images.

### ISSUE THREAD

**Issue by smyrgeorge** [store2be/pape-rs#140] opened 2020-03-23 07:13 UTC
Hello,

I have an array of images
```
"variables": {
	"profession": "WIZARD",
	"animal": "CAT",
	"images": ["woosh.jpeg", "woosh.jpeg"]
}
```

and a for loop in my template.
```
{% for image in images %}
  {{image}}
  \includegraphics{{{image}}}
{% endfor %}
```

I keep getting errors
```
Mar 23 06:59:47.003 ERRO Error rendering document: ErrorMessage { msg: "failed to add template: Error(Msg(\"Failed to parse \\\"/tmp/70d351e61da74142b5bf47d26679b73f/template.tex.tera\\\"\"), State { next_error: Some(Error(Msg(\"  --> 11:22\\n   |\\n11 |   \\\\includegraphics\\\\{{{image}}\\\\}␊\\n   |                      ^---\\n   |\\n   = expected a value that can be negated\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })" }., version: 0.4.2, module: papers::papers::renderer:224
Mar 23 06:59:47.011 ERRO Error to be reported to the callback URL: ErrorMessage { msg: "failed to add template: Error(Msg(\"Failed to parse \\\"/tmp/70d351e61da74142b5bf47d26679b73f/template.tex.tera\\\"\"), State { next_error: Some(Error(Msg(\"  --> 11:22\\n   |\\n11 |   \\\\includegraphics\\\\{{{image}}\\\\}␊\\n   |                      ^---\\n   |\\n   = expected a value that can be negated\"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } })" }., version: 0.4.2, module: papers::utils::callbacks:62
```

I think something weird is going with the escaping.
Is there a solution?

Regards
George S.

**Comment by smyrgeorge** [comment] 2020-03-23 07:41
I managed to find a solution.
```
{% for image in images %}
   \includegraphics{{image}}
{% endfor %}
```
```
"variables": {
	"profession": "WIZARD",
	"animal": "CAT",
	"images": ["{woosh.jpeg}", "{woosh.jpeg}"]
}
```
and i used `"no_escape_tex": true` in the json payload.
I think the issue can be closed.

**Comment by indifferentalex** [comment] 2020-03-24 14:51
Hi George, I wasn't able to reproduce the same escaping error you were getting unfortunately.

It wasn't working for me either however (with the string filename variables), I found [this tip](https://github.com/store2be/pape-rs/wiki/LaTeX-template-tips-and-tricks#latex-tera-curly-brackets-conflicts) mentioned in the wiki and it helped in getting the string reference to be used correctly by the `\includegraphics` macro call (e.g. `\includegraphics{% raw %}{{% endraw %}{{image}}{% raw %}}{% endraw %}`)

I'm not part of the original contributors (nor a maintainer sadly), however since the wiki does explicitly describe a workaround, I think it's safe to say that's the way to go, if you agree I would proceed and close the issue

**Comment by smyrgeorge** [comment] 2020-03-24 15:25
I agree and thanks for your help 😄

**Closed** 2020-03-24 15:46 UTC
